[build]
  command = "CI=false NEXT_TELEMETRY_DISABLED=1 npm run static"
  publish = "out"

[build.environment]
  CI = "false"
  NODE_VERSION = "16"
  NEXT_TELEMETRY_DISABLED = "1"
  ESLINT_NO_DEV_ERRORS = "true" 